### ISSUE TITLE
aredis pipeline does not work with Python 3.5.1

### ISSUE THREAD

**Issue by Rmaan** [NoneGG/aredis#77]
## Checklist

- Python version 3.5.1
- Does issue exists against the `master` branch of aredis? Yes

## Steps to reproduce
Use aredis and execute a pipeline with Python 3.5.1.

## Expected behavior
No error.

## Actual behavior
```
Traceback (most recent call last):
  File "c:\Users\2\AppData\Local\Programs\Python\Python35-32\Lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\prj\paintman\paintman\socket\async_socket_server.py", line 63, in process_queue
    commands = await async_read_server_command_chunk()
  File "C:\prj\paintman\paintman\socket\redis_protocol.py", line 89, in async_read_server_command_chunk
    res = await p.execute()
  File "C:\prj\paintman\env\lib\site-packages\aredis\pipeline.py", line 286, in execute
    return await exec(conn, stack, raise_on_error)
  File "C:\prj\paintman\env\lib\site-packages\aredis\pipeline.py", line 203, in _execute_transaction
    if isinstance(response, typing.Awaitable):
AttributeError: module 'typing' has no attribute 'Awaitable'
```

aredis will check being awaitable in this line of code:

https://github.com/NoneGG/aredis/blob/f662f3332021a1147ed55cd5a202aa9b37c44d0b/aredis/pipeline.py#L203

and from what I understand, `typing.Awaitable` is not available in all Python 3.5 versions (source: https://docs.python.org/3.5/whatsnew/changelog.html#id22). You could use `inspect` package to check an object being awaitable or not:
```
import inspect
if inspect.isawaitable(response):
    ...
```

**Comment by NoneGG** [comment]
Thanks for your advice, i will take a look at it as soon as possible~

**Comment by NoneGG** [comment]
@Rmaan The bug you reported is now fixed~ 
Thank you for you report sincerely and this issue will be closed.
It is always welcome to be open again if there are further problems related.
